### ISSUE TITLE
ERROR:  Error installing primesieve:

### ISSUE THREAD

**Issue by St1G** [robertjlooby/primesieve-ruby#2]
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing primesieve:
        ERROR: Failed to build gem native extension.

```
   ruby.exe extconf.rb
```

checking for primesieve.h... no
primesieve header is missing. please install primesieve
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Ruby193/bin/ruby
        --with-primesieve-dir
        --without-primesieve-dir
        --with-primesieve-include
        --without-primesieve-include=${primesieve-dir}/include
        --with-primesieve-lib
        --without-primesieve-lib=${primesieve-dir}/lib

**Comment by robertjlooby** [comment]
Sorry I missed this! Do you have the primesieve binary? They're available on http://primesieve.org/ or if you're using OSX and homebrew you can `brew install primesieve`
